services:
  - type: web
    name: pet-adoption
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn PetAdoption.wsgi:application --chdir PetAdoption
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
