services:
  - type: web
    name: pet-adoption-backend
    env: python
    rootDir: PetAdoption # This tells Render to only deploy this folder
    buildCommand: ../build.sh # Go one folder back to access build.sh
    startCommand: gunicorn PetAdoption.wsgi:application --chdir PetAdoption

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
