services:
  - type: web
    name: pet-adoption-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn PetAdoption.wsgi:application --chdir PetAdoption/PetAdoption
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHONPATH
        value: PetAdoption

