services:
  - type: web
    name: pet-adoption
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False